### ISSUE TITLE
bug displaying sneaker multiple times

### ISSUE THREAD

**Issue by edwinab1** [Hamadakram/Sneaker#15]
if I click on a button multiple times it shows the sneaker, the application stops, it does not solve to add try {} catch {} when creating the sneaker
the error points to this line : getLayout().startAnimation(AnimationUtils.loadAnimation(getContext(), R.anim.popup_hide));

10-02 01:46:31.620 1767-1767/com.edwin E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.edwin, PID: 1767
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.startAnimation(android.view.animation.Animation)' on a null object reference
                                                                               at com.irozon.sneaker.Sneaker$1.run(Sneaker.java:474)
                                                                               at android.os.Handler.handleCallback(Handler.java)
                                                                               at android.os.Handler.dispatchMessage(Handler.java)
                                                                               at android.os.Looper.loop(Looper.java)
                                                                               at android.app.ActivityThread.main(ActivityThread.java)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by bab55z** [comment]
same here

**Comment by pcharbonnier** [comment]
same here..

**Comment by pcharbonnier** [comment]
same here,
Still no answer ?

**Comment by Hamadakram** [comment]
Fixed. Update version to `1.0.3`
