### ISSUE TITLE
[BUG] When activity is closed, and sneaker is visible..the activity crashes

### ISSUE THREAD

**Issue by Akshshr** [Hamadakram/Sneaker#29]
Title says it all..

**Comment by Akshshr** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.startAnimation(android.view.animation.Animation)' on a null object reference
       at com.irozon.sneaker.Sneaker$1.run(Sneaker.java:474)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Comment by Hamadakram** [comment]
Fixed in version 2.0.0
